name: Deploy the application to Google Cloud Run
on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: Deploy job
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate into Google Cloud Platform
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Configure Docker to use Google Cloud Platform
        run: |
          gcloud auth configure-docker



      - name: Deploy Client to Cloud Run
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT}}
          APPLICATION_CREDENTIALS: ${{secrets.GCLOUD_AUTH}}
        with:
          args: run deploy fd-dispatch-client   --image gcr.io/{{ secrets.GCLOUD_PROJECT }}/fd-dispatch-client --project ${{ secrets.GCLOUD_PROJECT }}  --platform managed   --region us-central1   --allow-unauthenticated
      
      - name: Deploy API to Cloud Run
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: fd-dispatch-1576071994716
          APPLICATION_CREDENTIALS: ${{secrets.GCLOUD_AUTH}}
        with:
          args: run deploy fd-dispatch-api   --image gcr.io/{{ secrets.GCLOUD_PROJECT }}/fd-dispatch-api --project ${{ secrets.GCLOUD_PROJECT }}  --platform managed   --region us-central1   --allow-unauthenticated
