name: Deploy the application to Google Cloud Run
on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: Deploy job
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate into Google Cloud Platform
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Configure Docker to use Google Cloud Platform
        run: |
          gcloud auth configure-docker

      - name: Checkout the repository
        uses: actions/checkout@v1

      - name: Build Docker images
        run: |
          docker build ./api/ --tag gcr.io/${{ secrets.GCLOUD_PROJECT }}/fd-dispatch-api
          docker build ./client/ --build-arg REACT_APP_GOOGLE_MAPS_API_KEY=${{ secrets.MAPS_API_KEY }} --tag gcr.io/${{ secrets.GCLOUD_PROJECT }}/fd-dispatch-client

      - name: Push Docker Images
        run: |
          docker push gcr.io/${{ secrets.GCLOUD_PROJECT }}/fd-dispatch-client
          docker push gcr.io/${{ secrets.GCLOUD_PROJECT }}/fd-dispatch-api

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fd-dispatch-client   --image gcr.io/{{ secrets.GCLOUD_PROJECT }}/fd-dispatch-client --project ${{ secrets.GCLOUD_PROJECT }}  --platform managed   --region us-central1   --allow-unauthenticated
          gcloud run deploy fd-dispatch-api   --image gcr.io/{{ secrets.GCLOUD_PROJECT }}/fd-dispatch-api --project ${{ secrets.GCLOUD_PROJECT }}  --platform managed   --region us-central1   --allow-unauthenticated